#!/usr/bin/env php
<?php

foreach (array(__DIR__ . '/../../autoload.php', __DIR__ . '/vendor/autoload.php') as $file) {
    if (file_exists($file)) {
        define('COMPOSER_AUTOLOAD', $file);
        break;
    }
}

if (!defined('COMPOSER_AUTOLOAD')) {
    die(
        'You need to set up the project dependencies using the following commands:' . PHP_EOL .
        'wget http://getcomposer.org/composer.phar' . PHP_EOL .
        'php composer.phar install' . PHP_EOL
    );
}

require COMPOSER_AUTOLOAD;

use Symfony\Component\Console\Application;
use orakaro\IoC\gentool\GenCommand;
use orakaro\IoC\gentool\CleanCommand;

$application = new Application();
$application->add(new GenCommand);
$application->add(new CleanCommand);
$application->run();
